baseURL = "http://aalvarez.me/"
languageCode = "en-us"
title = "Andrés Álvarez"
highlighter = "pygments"
theme = "hyde"

paginate = 5
disqusShortname = "aalvarez-blog"
enableEmoji = true

# Code Highligting
pygmentsCodefences = true
pygmentsStyle = "colorful"


[params]
  themeColor = "theme-base-08"
  description = "Software Engineer & Web Developer"

  email = "andresalvarez353@gmail.com"
  github = "BigChief45"
  linkedin = "aalvarez4"
  instagram = "aalvarez300"
  rss = "feed.xml"
